export const FETCH_DATA = 'FETCH_DATA';
export const CHANGE_CURRENT_TAG = 'CHANGE_CURRENT_TAG';
export const ADD_NEW_TAG = 'ADD_NEW_TAG';
export const POST_NEW_TAG_SUCCESS = 'POST_NEW_TAG_SUCCESS';
export const POST_NEW_TAG_FAILED = 'POST_NEW_TAG_FAILED';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';